version: '3'

services:
  nginx:
    build: .
    ports:
      - "9001:9001"
    depends_on:
      - my_app

  my_app:
    build: ..
    environment:
    - SOCIAL_SERVER_ADDRESS=${SOCIAL_SERVER_ADDRESS}
