version: '3'

services:
  nginx:
    build: .
    ports:
      - "8443:8443"
    depends_on:
      - my_app

  my_app:
    image: laukik2002/media-go-upload:latest
    environment:
    - SOCIAL_SERVER_ADDRESS=${SOCIAL_SERVER_ADDRESS}
